deployment:
  tasks:
    - echo "Starting deployment"
    - /opt/cpanel/ea-nodejs16/bin/npm install
    - /opt/cpanel/ea-nodejs16/bin/npm run build
    - rsync -a --exclude='.git' --exclude='.cpanel.yml' build/ /home/$USER/public_html
    - echo "Deployment tasks completed"
